name: Build docker image and push to GHCR

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write
  attestations: write
  id-token: write

jobs:
  docker-build:
    runs-on: ubuntu-latest
    outputs:
      tagname: ${{ steps.output-tag-name.outputs.tagname }}
    steps:
      - uses: actions/checkout@v4
      - name: Fetch Repo Name
        id: repo-name
        run: echo "::set-output name=value::$(echo 'gitpod4' | awk -F '/' '{print $2}')"
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            ghcr.io/leanprover-community/${{ github.event.repository.name }}
          # generate Docker tags based on the following events/attributes
          tags: |
            type=ref,event=branch
            type=ref,event=tag
            type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
      # cached builds according to
      # https://github.com/docker/build-push-action/blob/d17cab8f420a2403aa182827208f8f957ccbf9a9/docs/advanced/cache.md#github-cache
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          # with future possibilities to do it to hub.docker.com
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Final tag name
        id: output-tag-name
        run: echo "::set-output name=tagname::${{ steps.meta.outputs.tags }}"
      - name: Build and push image
        uses: docker/build-push-action@v6
        with:
          # action can do checkout, but I don't know the exact subdir syntax
          context: .docker/gitpod/
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v2
        with:
          subject-name: ghcr.io/leanprover-community/${{ github.event.repository.name }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true
